name: CraftBook
main: com.sk89q.craftbook.bukkit.CraftBookPlugin
version: "${internalVersion}"
dev-url: http://dev.bukkit.org/server-mods/craftbook/
depend: [WorldEdit]
softdepend: [WorldGuard, ProtocolLib, Vault, FastAsyncWorldEdit]
api-version: 1.13
commands:
